version: "3.3"

services:
  orders-service:
    image: imarquez99/orders-service:latest
    ports:
      - "8080:8080"
    environment:
      - JWT_KEY=a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/orders
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=orders
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
