version: '3.7'
services:
  postgres:
    image: postgres:12.2
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=orders
    volumes:
      - ./postgres-data:/var/lib/postgresql/data