spring:
  application:
    name: orders-service
  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: password
# connect to database orders in PostgresSQL with password root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.7:5432/orders
    username: postgres
    password: root
  jpa:
    #database: H2
    #database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
message: "Hello from default profile"

jwt:
  key: ${JWT_KEY}
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000

---
spring:
  config:
    activate:
      on-profile:
        - dev
message: "Hello from dev profile"