version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../:/workspaces/${localWorkspaceFolderBasename}:cached
    command: sleep infinity
    network_mode: service:postgres

  # Override postgres service to expose port for dev container
  postgres:
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspaces:cached
    command: sleep infinity
    ports:
      - "5432:5432"

